In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [19]:
df = pd.read_csv('Social_Network_Ads.csv')

In [20]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [21]:
df.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [23]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [24]:
df.shape

(400, 5)

In [25]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [26]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [37]:
x = df.iloc[:, [2,3]].values
y = df.iloc[:, 4].values

In [46]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25, random_state=44)

In [54]:
x_train

array([[    20,  86000],
       [    41,  60000],
       [    29,  83000],
       [    37, 137000],
       [    42, 104000],
       [    41,  51000],
       [    33,  43000],
       [    40,  78000],
       [    35,  79000],
       [    27,  96000],
       [    37,  78000],
       [    36,  33000],
       [    47, 144000],
       [    41,  87000],
       [    35,  88000],
       [    31,  89000],
       [    56, 104000],
       [    42,  53000],
       [    35,  60000],
       [    56,  60000],
       [    35,  47000],
       [    45,  79000],
       [    47,  47000],
       [    44, 139000],
       [    37,  80000],
       [    38,  71000],
       [    47, 107000],
       [    37,  75000],
       [    22,  27000],
       [    20,  74000],
       [    36,  54000],
       [    28, 123000],
       [    49,  89000],
       [    42,  79000],
       [    41,  72000],
       [    27,  58000],
       [    36,  63000],
       [    37,  71000],
       [    29,  28000],
       [    53,  34000],


In [48]:
x_test.shape

(100, 2)

In [49]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [50]:
y_train.shape

(300,)

In [56]:
# Data Standardization
from sklearn.preprocessing import StandardScaler
s = StandardScaler()

In [57]:
x_train = s.fit_transform(x_train)
x_test = s.fit_transform(x_test)

In [58]:
x_train

array([[-1.63160808,  0.54552381],
       [ 0.35048427, -0.22953734],
       [-0.78213993,  0.45609368],
       [-0.02705713,  2.06583608],
       [ 0.44486962,  1.08210462],
       [ 0.35048427, -0.49782774],
       [-0.40459853, -0.7363081 ],
       [ 0.25609892,  0.30704346],
       [-0.21582783,  0.3368535 ],
       [-0.97091063,  0.84362426],
       [-0.02705713,  0.30704346],
       [-0.12144248, -1.03440854],
       [ 0.91679636,  2.2745064 ],
       [ 0.35048427,  0.57533386],
       [-0.21582783,  0.6051439 ],
       [-0.59336923,  0.63495395],
       [ 1.76626451,  1.08210462],
       [ 0.44486962, -0.43820765],
       [-0.21582783, -0.22953734],
       [ 1.76626451, -0.22953734],
       [-0.21582783, -0.61706792],
       [ 0.72802566,  0.3368535 ],
       [ 0.91679636, -0.61706792],
       [ 0.63364032,  2.12545617],
       [-0.02705713,  0.36666355],
       [ 0.06732822,  0.09837315],
       [ 0.91679636,  1.17153475],
       [-0.02705713,  0.21761332],
       [-1.44283738,

In [59]:
m = LogisticRegression()
m.fit(x_train,y_train)

LogisticRegression()

In [60]:
y_predicted = m.predict(x_test)

In [61]:
y_predicted

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [66]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predicted)
print(cm)

[[53  5]
 [19 23]]


In [68]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_predicted)*100
accuracy

76.0

In [69]:
TP = cm[0][0]
print(TP)

53


In [72]:
FP = cm[0][1]
FP

5

In [73]:
FN = cm[1][0]
FN

19

In [74]:
TN = cm[1][1]
TN

23

In [76]:
#Accuracy 
acc = ((TP+TN)/(TP+TN+FP+FN))*100
acc

76.0

In [78]:
#Error Rate
errorRate = ((FP+FN)/(TP+TN+FN+FP))*100
errorRate

24.0

In [79]:
#Precision
precision = (TP/(TP+FP))*100
precision

91.37931034482759

In [80]:
#Recall
recall = (TP/(TP+FN))*100
recall

73.61111111111111

In [81]:
#Specificity
specificity = (TN/(TN+FP))*100
specificity

82.14285714285714